### PR TITLE
[mod_python3] Fix build on Python 3.10+

### LINKED ISSUE #2145: build error on mod_python3 on bookworm
```
making all mod_python3
make[6]: Entering directory '/build/freeswitch-1.10.9/src/mod/languages/mod_python3' 
  CC       mod_python3_la-mod_python3.lo 
mod_python3.c: In function 'print_python_error':
mod_python3.c:157:73: error: invalid use of incomplete typedef 'PyFrameObject' {aka 'struct _frame'} 
  157 |                                         PyString_AsString(pyTB->tb_frame->f_code->co_filename),
      |                                                                         ^~                                                                                          │
mod_python3.c:159:73: error: invalid use of incomplete typedef 'PyFrameObject' {aka 'struct _frame'} 
  159 |                                         PyString_AsString(pyTB->tb_frame->f_code->co_name) ); 
      |                                                                         ^~                                                                                          │
make[6]: *** [Makefile:763: mod_python3_la-mod_python3.lo] Error 1
make[6]: Leaving directory '/build/freeswitch-1.10.9/src/mod/languages/mod_python3'
```

Versions:
```
Get: 166 http://deb.debian.org/debian bookworm/main amd64 python3-all amd64 3.11.2-1+b1 [1056 B] 
Get: 167 http://deb.debian.org/debian bookworm/main amd64 python3.11-dev amd64 3.11.2-6 [615 kB]
Get: 168 http://deb.debian.org/debian bookworm/main amd64 python3-dev amd64 3.11.2-1+b1 [26.2 kB]
Get: 169 http://deb.debian.org/debian bookworm/main amd64 python3-pkg-resources all 66.1.1-1 [296 kB]
Get: 170 http://deb.debian.org/debian bookworm/main amd64 python3-setuptools all 66.1.1-1 [521 kB]
```

autoconf:
```
checking for python... no
configure: WARNING: Could not find python, mod_python will not build, use --with-python to specify the location
checking for python3... /usr/bin/python3
checking python3 version... 3.11.2
checking for python3 distutils... yes
checking location of python3 site-packages... /usr/lib/python3/dist-packages
checking python3 libdir... /usr/lib/x86_64-linux-gnu
checking for main in -lpython3.11... yes
checking for PyThread_init_thread... yes
configure: Your python3 seems OK, do not forget to enable mod_python3 in modules.conf
```

### PR DESCRIPTION
**Pull request by linuxmaniac**

### CODE REVIEW

**Review by andywolk — CHANGES_REQUESTED** [review]

File: src/mod/languages/mod_python3/mod_python3.c [hunk 1]
```diff
@@ -153,10 +156,22 @@ static void print_python_error(const char * script)
 
 		/* Traceback */
 		do {
+#if PY_VERSION_HEX >= 0x030B0000
+			if(pyTB->tb_frame != NULL) {
+				pcode = PyFrame_GetCode(pyTB->tb_frame);
+			} else {
+				pcode = NULL;
+			}
+			sprintf((char*)sTemp, "\n\tFile: \"%s\", line %i, in %s",
```
[the remark this answers is not in the document]
Comment (andywolk) [reply src/mod/languages/mod_python3/mod_python3.c]: `sizeof` would be better and there is a misisng new line after the `if` block still.

[the remark this answers is not in the document]
Comment (linuxmaniac) [reply src/mod/languages/mod_python3/mod_python3.c]: @andywolk is that what you want?

[the remark this answers is not in the document]
Comment (andywolk) [reply src/mod/languages/mod_python3/mod_python3.c]: Perfect. Thank you!
