### ISSUE TITLE
mod_pocketsphinx compilation error with GCC 14/sphinxbase-0.8.tar.gz

### ISSUE THREAD

**Issue by space88man** [signalwire/freeswitch#2656]
**Describe the bug**
mod_pocketsphinx doesn't build with GCC 14 due to the sphinxbase-0.8.tar.gz dependency which has a function (yyparse) with no prototype. This is now an error with GCC 14

**To Reproduce**
1. FreeSWITCH 1.10.12 with configuration including mod_pocketsphinx
2. Build with GCC 14 

**Expected behavior**
Compilation succeeds

**Package version or git hash**
 - Version 1.10.12

**Build logs**
Compilation error in `sphinxbase-0.8/src/libsphinxbase/lm/jsgf.c` as `yyparse` has no prototypte

This is the needed patch:
```patch
diff '--color=auto' -ur a/src/libsphinxbase/lm/jsgf.c sphinxbase-0.8/src/libsphinxbase/lm/jsgf.c
--- a/src/libsphinxbase/lm/jsgf.c       2012-12-05 22:06:07.000000000 +0800
+++ sphinxbase-0.8/src/libsphinxbase/lm/jsgf.c  2024-12-01 19:57:04.138416256 +0800
@@ -730,6 +730,7 @@
     return NULL;
 }
 
+int yyparse (void* yyscanner, jsgf_t *jsgf);
 jsgf_t *
 jsgf_parse_file(const char *filename, jsgf_t *parent)
 {
```
