### ISSUE TITLE
1.10.9 macOS build failure caused by PR #1838 mod_sofia

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1840]
**Describe the bug**
Make on macOS now gets the error below. Since 1.10.8 release builds fine and I can only find one change since then (#1838) it may be related.

duplicate symbol '_mod_sofia_load' in:
    test/test_sofia_funcs-test_sofia_funcs.o
    ./.libs/libsofiamod.a(libsofiamod_la-mod_sofia.o)
ld: 17 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [test/test_sofia_funcs] Error 1
make[3]: *** [mod_sofia-all] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**To Reproduce**
normal download, ns, config, make.

**Package version or git hash**
1.10.9 442ebe344b920298003df8f60cf1c3c130011d52

[07 FreeSWITCH make.txt](https://github.com/signalwire/freeswitch/files/9862121/07.FreeSWITCH.make.txt)

**Comment by MarioG-X** [comment]
Definitely #1838. I manually reversed the. line patch and FS built fine.

**Comment by andywolk** [comment]
@MarioG-X Please try this out https://github.com/signalwire/freeswitch/pull/1910

**Comment by MarioG-X** [comment]
Yes that did it, thank you! Once it's in master I can get back to testing each time I see a master change.

Sorry to take so long I should have just applied the changes manually instead of figuring out how to apply them from your repo. I would up installing GitHub desktop and still don't know how I got the. changes applied. Certainly not intuitive.

**Comment by MarioG-X** [comment]
What will it take to get #1910 into master?
