### ISSUE TITLE
FS does not compile with GCC 11.1.x

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#1198]
**Describe the bug**
cannot compile with gcc 11.1.x (Linux Fedora 34)

```
src/switch_utils.c: In function ‘switch_simple_email’:
src/switch_utils.c:1326:13: error: ‘filename’ may be used uninitialized [-Werror=maybe-uni                                                                                                                                                    nitialized]
 1326 |         if (unlink(filename) != 0) {
      |             ^~~~~~~~~~~~~~~~
In file included from ./src/include/switch_platform.h:123,
                 from ./src/include/switch.h:112,
                 from src/switch_utils.c:35:
/usr/include/unistd.h:838:12: note: by argument 1 of type ‘const char *’ to ‘unlink’ decla                                                                                                                                                    red here
  838 | extern int unlink (const char *__name) __THROW __nonnull ((1));
      |            ^~~~~~
src/switch_utils.c:1120:14: note: ‘filename’ declared here
 1120 |         char filename[80], buf[B64BUFFLEN];
      |              ^~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2520: src/libfreeswitch_la-switch_utils.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
src/switch_rtp.c:4390:117: error: argument 5 of type ‘switch_rtp_flag_t[51]’ with mismatch                                                                                                                                                    ed bound [-Werror=array-parameter=]
 4390 |                                                                                                                                                                                                                                                       switch_rtp_flag_t flags[SWITCH_RTP_FLAG_INVALID], char *timer_name, const                                                                                                                                                     char **err, switch_memory_pool_t *pool)
      |                                                                                                                                                                                                                                                       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./src/include/switch.h:132,
                 from src/switch_rtp.c:33:
./src/include/switch_rtp.h:237:117: note: previously declared as ‘switch_rtp_flag_t[]’
  237 |                                                                                                                                                                                                                                                       switch_rtp_flag_t flags[], char *timer_name, const char **err, switch_memo                                                                                                                                                    ry_pool_t *pool);
      |                                                                                                                                                                                                                                                       ~~~~~~~~~~~~~~~~~~^~~~~~~
src/switch_rtp.c:4609:109: error: argument 8 of type ‘switch_rtp_flag_t[51]’ with mismatch                                                                                                                                                    ed bound [-Werror=array-parameter=]
 4609 |                                                                                                                                                                                                                                               switch_rtp_flag_t flags[SWITCH_RTP_FLAG_INVALID], char *timer_name, const char **e                                                                                                                                                    rr, switch_memory_pool_t *pool,
      |                                                                                                                                                                                                                                               ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./src/include/switch.h:132,
                 from src/switch_rtp.c:33:
./src/include/switch_rtp.h:263:109: note: previously declared as ‘switch_rtp_flag_t[]’
  263 |                                                                                                                                                                                                                                               switch_rtp_flag_t flags[], char *timer_name, const char **err, switch_memory_pool_                                                                                                                                                    t *pool, switch_port_t bundle_internal_ports, switch_port_t bundle_external_port);
      |                                                                                                                                                                                                                                               ~~~~~~~~~~~~~~~~~~^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2548: src/libfreeswitch_la-switch_rtp.lo] Error 1
src/switch_core_media.c:2225:111: error: argument 2 of type ‘switch_core_media_flag_t[15]’                                                                                                                                                     with mismatched bound [-Werror=array-parameter=]
 2225 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *sm                                                                                                                                                    h, switch_core_media_flag_t flags[SCMF_MAX])
      |                                                                                                                                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from ./src/include/switch.h:143,
                 from src/switch_core_media.c:33:
./src/include/switch_core_media.h:200:111: note: previously declared as ‘switch_core_media                                                                                                                                                    _flag_t[]’
  200 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *sm                                                                                                                                                    h, switch_core_media_flag_t flags[]);
      |                                                                                                                                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2471: src/libfreeswitch_la-switch_core_media.lo] Error 1
make[1]: Leaving directory '/home/src/freeswitch'
make: *** [Makefile:1432: all] Error 2
```

**Comment by andywolk** [comment]
I will be happy to review a PR for this.

**Comment by crienzo** [comment]
PR #1199

**Comment by andywolk** [comment]
Fixed

**Comment by ROBERT-MCDOWELL** [comment]
I still have a compilation error after made git pull

src/switch_rtp.c:4390:117: error: argument 5 of type ‘switch_rtp_flag_t[51]’ with mismatched bound [-Werror=array-parameter=]
 4390 |                                                                                                   switch_rtp_flag_t flags[SWITCH_RTP_FLAG_INVALID], char *timer_name, const char **err, switch_memory_pool_t *pool)
      |                                                                                                   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./src/include/switch.h:132,
                 from src/switch_rtp.c:33:
./src/include/switch_rtp.h:237:117: note: previously declared as ‘switch_rtp_flag_t[]’
  237 |                                                                                                   switch_rtp_flag_t flags[], char *timer_name, const char **err, switch_memory_pool_t *pool);
      |                                                                                                   ~~~~~~~~~~~~~~~~~~^~~~~~~
src/switch_rtp.c:4609:109: error: argument 8 of type ‘switch_rtp_flag_t[51]’ with mismatched bound [-Werror=array-parameter=]
 4609 |                                                                                           switch_rtp_flag_t flags[SWITCH_RTP_FLAG_INVALID], char *timer_name, const char **err, switch_memory_pool_t *pool,
      |                                                                                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./src/include/switch.h:132,
                 from src/switch_rtp.c:33:
./src/include/switch_rtp.h:263:109: note: previously declared as ‘switch_rtp_flag_t[]’
  263 |                                                                                           switch_rtp_flag_t flags[], char *timer_name, const char **err, switch_memory_pool_t *pool, switch_port_t bundle_internal_ports, switch_port_t bundle_external_port);
      |                                                                                           ~~~~~~~~~~~~~~~~~~^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2548: src/libfreeswitch_la-switch_rtp.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
src/switch_core_media.c:2225:111: error: argument 2 of type ‘switch_core_media_flag_t[15]’ with mismatched bound [-Werror=array-parameter=]
 2225 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[SCMF_MAX])
      |                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from ./src/include/switch.h:143,
                 from src/switch_core_media.c:33:
./src/include/switch_core_media.h:200:111: note: previously declared as ‘switch_core_media_flag_t[]’
  200 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[]);
      |                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~

**Comment by crienzo** [comment]
It looks like GCC 11.1 is pretty far from working. So, we will not be able to fix all these issues for you as we do not currently support Fedora. We can, however, review PRs with the fixes.

**Comment by ROBERT-MCDOWELL** [comment]
no worry, I just follow my experiences with FS, knowing that Fedora is the pre OS of redhat.

**Comment by ROBERT-MCDOWELL** [comment]
FYI, just have one warning considered as an error, I think it's nothing to do with gcc version

src/switch_core_media.c:2225:111: error: argument 2 of type ‘switch_core_media_flag_t[15]’ with mismatched bound [-Werror=array-parameter=]
 2225 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[SCMF_MAX])
      |                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from ./src/include/switch.h:143,
                 from src/switch_core_media.c:33:
./src/include/switch_core_media.h:200:111: note: previously declared as ‘switch_core_media_flag_t[]’
  200 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[]);
      |                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2471: src/libfreeswitch_la-switch_core_media.lo] Error 1
make[1]: Leaving directory '/home/src/freeswitch'
make: *** [Makefile:1432: all] Error 2

**Comment by ROBERT-MCDOWELL** [comment]
About gcc 11 changes, here is a useful comment from a github project that had such kind of issue
https://github.com/ARMmbed/mbedtls/pull/3848/commits/2c424570e2a85e21273313808e8c5efcf1cfc9d7

**Comment by ROBERT-MCDOWELL** [comment]
I solved it with these changes (don't know if it's correct but compiles well now)

./src/include/switch_core_media.h:200:111:
- SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[]);
+ SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[SCMF_MAX]);

src/switch_rtp.c:4390:117:
- switch_rtp_flag_t flags[SWITCH_RTP_FLAG_INVALID], char *timer_name, const char **err, switch_memory_pool_t *pool)
+ switch_rtp_flag_t flags[], char *timer_name, const char **err, switch_memory_pool_t *pool)

src/switch_rtp.c:4609:109:
- switch_rtp_flag_t flags[SWITCH_RTP_FLAG_INVALID], char *timer_name, const char **err, switch_memory_pool_t *pool,
+ switch_rtp_flag_t flags[], char *timer_name, const char **err, switch_memory_pool_t *pool,
