### ISSUE TITLE
Crash on conference

### ISSUE THREAD

**Issue by fx02** [signalwire/freeswitch#661]
We tried to upgrade from 1.8.7 to 1.10.3 but every time we try to establish conference via event socket and join two calls in conference FS would crash. If you need anything else I'll collect.

OS: FreeBSD 11.3
FS version: 1.10.3
Core dump: https://buzanic.com/temp/freeswitch_core.zip
log: https://buzanic.com/temp/fs_log.zip

**Comment by andywolk** [comment]
Try reproducing under valgrind and if success show the log it produces.

**Comment by fx02** [comment]
Here it is, valgring log + core: https:/buzanic.com/temp/fs_valgrind_logs.zip

**Comment by andywolk** [comment]
Please upload a backtrace from gdb

**Comment by fx02** [comment]
GDB: https://buzanic.com/temp/backtrace.log

**Comment by andywolk** [comment]
How old is your gdb?

**Comment by fx02** [comment]
v6.1.1, yeah I get it, this is with v9.1:
https://buzanic.com/temp/backtrace_new.log

**Comment by andywolk** [comment]
Hard to say anything as there are no line numbers.

**Comment by fx02** [comment]
Could debug build help?

**Comment by andywolk** [comment]
Sure. Please repeat everything using debugging build.

**Comment by fx02** [comment]
https://buzanic.com/temp/fs_debug_log.zip
https://pastebin.freeswitch.org/view/a4447507

Hepe this helps, if not, please point me how to reproduce correct logs as I'm using https://freeswitch.org/confluence/display/FREESWITCH/Debugging+Freeswitch for these.

**Comment by fx02** [comment]
We tried same thing on Red Hat 7.8 and got same issue with 1.10.3 version so I guess something was introduced in 1.10, it works great on 1.8.7, no crash, will test 1.10.1 later and report back.

**Comment by mjerris** [comment]
can you git bisect to find the patch that caused the issue please

**Comment by fx02** [comment]
Building with scripts/ci/rpmbuilder.sh, stuck on:
kazoo_ei_utils.c:221:3: error: implicit declaration of function 'ei_x_encode_map_header' [-Werror=implicit-function-declaration]

**Comment by fx02** [comment]
Tried 1.10.6 today on CentOS7, after this FS still crashes:

`nua_stack.c:573 nua_stack_signal() nua(0x25a47e0): recv signal r_respond 401 Unauthorized
nua.c:925 nua_handle_destroy() nua: nua_handle_destroy: entering
nua_params.c:484 nua_stack_set_params() nua: nua_stack_set_params: entering
nua_stack.c:529 nua_signal() nua(0x25a47e0): sent signal r_destroy
soa.c:403 soa_set_params() soa_set_params(static::0x1e272c0, ...) called
nua.c:370 nua_handle_magic() nua: nua_handle_magic: entering
nua.c:925 nua_handle_destroy() nua: nua_handle_destroy: entering
nua.c:1169 nua_handle_unref_user() nua nua_handle_unref_user(0x25a47e0): entering
nua_stack.c:529 nua_signal() nua(0x25a47e0): sent signal r_handle_unref
nua.c:1162 nua_unref_user() nua: nua_unref_user: entering
nua_stack.c:529 nua_signal() nua((nil)): sent signal r_unref
tport.c:3286 tport_tsend() tport_tsend(0x80c8000) tpn = WSS/EXTERNAL.CLIENT.IP.ADDRESS:63000
tport_type_ws.c:312 tport_send_stream_ws() tport_ws_writevec: vec 0x80c81f0 0x9fc4c00 715 (0)
tport.c:3623 tport_vsend() tport_vsend(0x80c8000): 715 bytes of 715 to wss/EXTERNAL.CLIENT.IP.ADDRESS:63000
tport.c:3521 tport_send_msg() tport_vsend returned 715
tport.c:2311 tport_set_secondary_timer() tport(0x80c8000): reset timer
nta.c:6826 incoming_reply() nta: sent 401 Unauthorized for REGISTER (261)
nta.c:5773 incoming_free() nta: incoming_free(0x2180f00)
nua_stack.c:569 nua_stack_signal() nua(0x25a47e0): recv signal r_destroy
nua_dialog.c:397 nua_dialog_usage_remove_at() nua(0x25a47e0): removing registrar usage
tport.c:4251 tport_release() tport_release(0x80c8000): (nil) by 0x25a47e0 with (nil)
tport.c:2311 tport_set_secondary_timer() tport(0x80c8000): reset timer
nta.c:4499 nta_leg_destroy() nta_leg_destroy((nil))
soa.c:356 soa_destroy() soa_destroy(static::0x1e272c0) called
nua_stack.c:569 nua_stack_signal() nua(0x25a47e0): recv signal r_handle_unref
nua_stack.c:569 nua_stack_signal() nua((nil)): recv signal r_unref
tport.c:2795 tport_wakeup() tport_wakeup(0x80c8000): events IN
tport.c:2893 tport_recv_event() tport_recv_event(0x80c8000)
tport.c:3234 tport_recv_iovec() tport_recv_iovec(0x80c8000) msg 0x2544800 from (wss/EXTERNAL.CLIENT.IP.ADDRESS:63000) has 932 bytes, veclen = 1
tport.c:3052 tport_deliver() tport_deliver(0x80c8000): msg 0x2544800 (932 bytes) from wss/EXTERNAL.CLIENT.IP.ADDRESS:63000/sips next=(nil)
nta.c:2909 agent_recv_request() nta: received REGISTER sip:FREESWITCH.PUBLIC.IP.ADDRESS SIP/2.0 (CSeq 262)
nta.c:3203 agent_check_request_via() nta: Via check: received=EXTERNAL.CLIENT.IP.ADDRESS
nta.c:3277 agent_aliases() nta: canonizing sip:FREESWITCH.PUBLIC.IP.ADDRESS with contact
nta.c:3114 agent_recv_request() nta: REGISTER (262) going to a default leg
nua_server.c:102 nua_stack_process_request() nua: nua_stack_process_request: entering
nua_stack.c:905 nh_create() nua: nh_create: entering
nua_common.c:108 nh_create_handle() nua: nh_create_handle: entering
nua_params.c:484 nua_stack_set_params() nua: nua_stack_set_params: entering
soa.c:280 soa_clone() soa_clone(static::0x1e26000, 0x1703380, 0x25a47e0) called
soa.c:403 soa_set_params() soa_set_params(static::0x1e272c0, ...) called
nua_dialog.c:338 nua_dialog_usage_add() nua(0x25a47e0): adding registrar usage
tport.c:4189 tport_pend() tport_pend(0x80c8000): pending (nil) for wss/EXTERNAL.CLIENT.IP.ADDRESS:63000 (already 0)
nua_stack.c:271 nua_stack_event() nua(0x25a47e0): event i_register 100 Trying
tport.c:2311 tport_set_secondary_timer() tport(0x80c8000): reset timer
nua_stack.c:359 nua_application_event() nua: nua_application_event: entering
nua.c:370 nua_handle_magic() nua: nua_handle_magic: entering
nua_common.c:108 nh_create_handle() nua: nh_create_handle: entering
nua.c:346 nua_handle_bind() nua: nua_handle_bind: entering
nua.c:667 nua_message() nua: nua_message: entering
nua_stack.c:529 nua_signal() nua(0x2fdfd40): sent signal r_message
nua_stack.c:569 nua_stack_signal() nua(0x2fdfd40): recv signal r_message
nua_params.c:484 nua_stack_set_params() nua: nua_stack_set_params: entering
soa.c:280 soa_clone() soa_clone(static::0x1e26000, 0x1703380, 0x2fdfd40) called
soa.c:403 soa_set_params() soa_set_params(static::0x1e274a0, ...) called
soa.c:403 soa_set_params() soa_set_params(static::0x1e274a0, ...) called
nta.c:2694 nta_tpn_by_url() nta: selecting scheme sip
tport.c:4617 tport_by_name() tport(0x161f900): found 0x2554000 by name wss/EXTERNAL.CLIENT.IP.ADDRESS:57967
tport.c:3286 tport_tsend() tport_tsend(0x2554000) tpn = wss/EXTERNAL.CLIENT.IP.ADDRESS:57967
tport_type_ws.c:312 tport_send_stream_ws() tport_ws_writevec: vec 0x25541f0 0x9fc5400 686 (0)
tport_type_ws.c:312 tport_send_stream_ws() tport_ws_writevec: vec 0x25541f0 0x285dcc0 25 (0)
tport.c:3623 tport_vsend() tport_vsend(0x2554000): 711 bytes of 711 to wss/EXTERNAL.CLIENT.IP.ADDRESS:57967
tport.c:3521 tport_send_msg() tport_vsend returned 711
tport.c:2311 tport_set_secondary_timer() tport(0x2554000): reset timer
nta.c:8348 outgoing_send() nta: sent MESSAGE (37062900) to wss/EXTERNAL.CLIENT.IP.ADDRESS:57967
tport.c:4189 tport_pend() tport_pend(0x2554000): pending 0x9fc5000 for wss/EXTERNAL.CLIENT.IP.ADDRESS:57967 (already 1)
tport.c:2795 tport_wakeup() tport_wakeup(0x2554000): events IN
tport.c:2893 tport_recv_event() tport_recv_event(0x2554000)
tport.c:3234 tport_recv_iovec() tport_recv_iovec(0x2554000) msg 0x9fc5800 from (wss/EXTERNAL.CLIENT.IP.ADDRESS:57967) has 355 bytes, veclen = 1
tport.c:3052 tport_deliver() tport_deliver(0x2554000): msg 0x9fc5800 (355 bytes) from wss/EXTERNAL.CLIENT.IP.ADDRESS:57967/sips next=(nil)
nta.c:3328 agent_recv_response() nta: received 200 OK for MESSAGE (37062900)
nta.c:3395 agent_recv_response() nta: 200 OK is going to a transaction
nta.c:9642 outgoing_estimate_delay() nta_outgoing: RTT is 44.581 ms
tport.c:4251 tport_release() tport_release(0x2554000): 0x9fc5000 by 0x1e122c0 with 0x9fc5800
nua_stack.c:271 nua_stack_event() nua(0x2fdfd40): event r_message 200 OK
nta.c:8774 outgoing_free() nta: outgoing_free(0x1e122c0)
tport.c:2311 tport_set_secondary_timer() tport(0x2554000): reset timer
nua_stack.c:359 nua_application_event() nua: nua_application_event: entering
nua.c:346 nua_handle_bind() nua: nua_handle_bind: entering
nua.c:883 nua_respond() nua: nua_respond: entering
nua_stack.c:529 nua_signal() nua(0x25a47e0): sent signal r_respond
nua.c:1169 nua_handle_unref_user() nua nua_handle_unref_user(0x25a47e0): entering
nua_stack.c:529 nua_signal() nua(0x25a47e0): sent signal r_handle_unref
nua.c:1162 nua_unref_user() nua: nua_unref_user: entering
nua_stack.c:529 nua_signal() nua((nil)): sent signal r_unref
nua_stack.c:573 nua_stack_signal() nua(0x25a47e0): recv signal r_respond 200 OK
nua.c:370 nua_handle_magic() nua: nua_handle_magic: entering
nua_params.c:484 nua_stack_set_params() nua: nua_stack_set_params: entering
nua.c:346 nua_handle_bind() nua: nua_handle_bind: entering
nua.c:925 nua_handle_destroy() nua: nua_handle_destroy: entering
soa.c:403 soa_set_params() soa_set_params(static::0x1e272c0, ...) called
nua_stack.c:529 nua_signal() nua(0x2fdfd40): sent signal r_destroy
nua.c:1169 nua_handle_unref_user() nua nua_handle_unref_user(0x2fdfd40): entering
nua_stack.c:529 nua_signal() nua(0x2fdfd40): sent signal r_handle_unref
nua.c:1162 nua_unref_user() nua: nua_unref_user: entering
nua_stack.c:529 nua_signal() nua((nil)): sent signal r_unref
tport.c:3286 tport_tsend() tport_tsend(0x80c8000) tpn = WSS/EXTERNAL.CLIENT.IP.ADDRESS:63000
tport_type_ws.c:312 tport_send_stream_ws() tport_ws_writevec: vec 0x80c81f0 0x9fc4c00 694 (0)
tport.c:3623 tport_vsend() tport_vsend(0x80c8000): 694 bytes of 694 to wss/EXTERNAL.CLIENT.IP.ADDRESS:63000
tport.c:3521 tport_send_msg() tport_vsend returned 694
tport.c:2311 tport_set_secondary_timer() tport(0x80c8000): reset timer
nta.c:6826 incoming_reply() nta: sent 200 OK for REGISTER (262)
nta.c:5773 incoming_free() nta: incoming_free(0x2180f00)
nua_stack.c:569 nua_stack_signal() nua(0x25a47e0): recv signal r_handle_unref
nua_stack.c:569 nua_stack_signal() nua((nil)): recv signal r_unref
nua_stack.c:569 nua_stack_signal() nua(0x2fdfd40): recv signal r_destroy
nta.c:4499 nta_leg_destroy() nta_leg_destroy((nil))
soa.c:356 soa_destroy() soa_destroy(static::0x1e274a0) called
nua_stack.c:569 nua_stack_signal() nua(0x2fdfd40): recv signal r_handle_unref
nua_stack.c:569 nua_stack_signal() nua((nil)): recv signal r_unref
2021-06-09 12:10:48.119277 [DEBUG] mod_commands.c:5200 Command chat(sip|Service|internal/extern.60c09397b7af4d5096352f8b@FREESWITCH.PUBLIC.IP.ADDRESS|{"pingIntervalSeconds":3}):
Sent
2021-06-09 12:10:48.119277 [DEBUG] switch_scheduler.c:147 Deleting task 14 sched_api_function (bgapi)
2021-06-09 12:10:48.119277 [DEBUG] switch_scheduler.c:263 Added task 15 sched_api_function (bgapi) to run at 1623233451`

GDB log:
`Core was generated by `/usr/bin/freeswitch -nc'.
Program terminated with signal 11, Segmentation fault.
#0  __strcmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
164             movdqu  (%rdi), %xmm1
Missing separate debuginfos, use: debuginfo-install postgresql-libs-9.2.24-4.el7_8.x86_64
(gdb) bt
#0  __strcmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
#1  0x00002b8d2d94ea17 in event_handler (event=0x71cfce0) at mod_event_socket.c:380
#2  0x00002b8d23a610de in switch_event_deliver (event=0x2b8d23261c70) at src/switch_event.c:410
#3  0x00002b8d23a60e71 in switch_event_dispatch_thread (thread=0x16bbb30, obj=0x160f7e8) at src/switch_event.c:339
#4  0x00002b8d23cf2f57 in dummy_worker () from /usr/lib64/libfreeswitch.so.1
#5  0x00002b8d271b7ea5 in start_thread (arg=0x2b8d23262700) at pthread_create.c:307
#6  0x00002b8d27e299fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)

`

**Comment by fx02** [comment]
fixed in https://github.com/signalwire/freeswitch/pull/1451
